version: "3.8"

services:
  backend:
    build: ./url-shortener-backend
    container_name: url-backend
    restart: unless-stopped
    env_file:
      - ./url-shortener-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./url-shortener-frontend
    container_name: url-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: url-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
